# Generated by Django 3.0.5 on 2020-11-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='unit',
            new_name='dimension',
        ),
    ]
