# Generated by Django 3.0.5 on 2020-12-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201103_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='style',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
